name: run automated tests

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  example_job:
    runs-on: ubuntu_latest
    steps:
      - uses: actions/checkout@v3
      - name: example step
        run: echo "Hello World"
